CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token    VARCHAR(255)                            NOT NULL,
    phone    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    UNIQUE (token),
    UNIQUE (phone)
);

CREATE INDEX IF NOT EXISTS user_token ON users (token);
CREATE INDEX IF NOT EXISTS user_phone ON users (phone);