CREATE TABLE IF NOT EXISTS organization
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    owner_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_organization PRIMARY KEY (id)
);

ALTER TABLE organization
    DROP CONSTRAINT IF EXISTS FK_ORGANIZATION_ON_OWNER;
ALTER TABLE organization
    ADD CONSTRAINT FK_ORGANIZATION_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

CREATE INDEX IF NOT EXISTS organization_owner ON organization (owner_id);