CREATE TABLE IF NOT EXISTS scope
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_scope PRIMARY KEY (id),
    UNIQUE (type)
);

INSERT INTO scope (type)
VALUES ('ORGANIZATION_UPDATE');

CREATE TABLE IF NOT EXISTS role
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    description     VARCHAR(255),
    owner bool DEFAULT false NOT NULL,
    organization_id BIGINT,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

ALTER TABLE role
    DROP CONSTRAINT IF EXISTS FK_ROLE_ON_ORGANIZATION;
ALTER TABLE role
    ADD CONSTRAINT FK_ROLE_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organization (id);
CREATE INDEX IF NOT EXISTS role_organization ON role (organization_id);
CREATE INDEX IF NOT EXISTS role_name ON role (name);

CREATE TABLE role_scopes
(
    role_id   BIGINT NOT NULL,
    scopes_id BIGINT NOT NULL
);

ALTER TABLE role_scopes
    DROP CONSTRAINT IF EXISTS fk_rolsco_on_role;
ALTER TABLE role_scopes
    ADD CONSTRAINT fk_rolsco_on_role FOREIGN KEY (role_id) REFERENCES role (id);
CREATE INDEX IF NOT EXISTS role_id ON role_scopes (role_id);

ALTER TABLE role_scopes
    DROP CONSTRAINT IF EXISTS fk_rolsco_on_scope;
ALTER TABLE role_scopes
    ADD CONSTRAINT fk_rolsco_on_scope FOREIGN KEY (scopes_id) REFERENCES scope (id);
CREATE INDEX IF NOT EXISTS scopes_id ON role_scopes (scopes_id);