CREATE TABLE employee
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active          BOOLEAN                                 NOT NULL DEFAULT true,
    user_id         BIGINT                                  NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    role_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (id),
    UNIQUE (user_id, organization_id)
);

ALTER TABLE employee
    DROP CONSTRAINT IF EXISTS FK_EMPLOYEE_ON_ORGANIZATION;
ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organization (id);


ALTER TABLE employee
    DROP CONSTRAINT IF EXISTS FK_EMPLOYEE_ON_ROLE;
ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);


ALTER TABLE employee
    DROP CONSTRAINT IF EXISTS FK_EMPLOYEE_ON_USER;
ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX IF NOT EXISTS employee_organization ON employee (organization_id);
CREATE INDEX IF NOT EXISTS employee_role ON employee (role_id);
CREATE INDEX IF NOT EXISTS employee_user ON employee (user_id);