CREATE TABLE employee_test
(
    employee_id BIGINT NOT NULL,
    test_id     BIGINT NOT NULL,
    CONSTRAINT pk_employee_test PRIMARY KEY (employee_id, test_id)
);

CREATE TABLE test
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    time_limit      INTEGER                                 NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_test PRIMARY KEY (id)
);

ALTER TABLE test
    ADD CONSTRAINT FK_TEST_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organization (id);
CREATE INDEX IF NOT EXISTS test_organization ON test (organization_id);

ALTER TABLE employee_test
    ADD CONSTRAINT fk_emptes_on_employee_aggregate FOREIGN KEY (employee_id) REFERENCES employee (id);
CREATE INDEX IF NOT EXISTS employee_test_employee ON employee_test (employee_id);

ALTER TABLE employee_test
    ADD CONSTRAINT fk_emptes_on_test_aggregate FOREIGN KEY (test_id) REFERENCES test (id);
CREATE INDEX IF NOT EXISTS employee_test_test ON employee_test (test_id);

CREATE TABLE question
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text       VARCHAR(255)                            NOT NULL,
    one_answer BOOLEAN                                 NOT NULL,
    test_id    BIGINT,
    CONSTRAINT pk_question PRIMARY KEY (id)
);

ALTER TABLE question
    ADD CONSTRAINT FK_QUESTION_ON_TEST FOREIGN KEY (test_id) REFERENCES test (id);
CREATE INDEX IF NOT EXISTS question_test ON question (test_id);

CREATE TABLE option
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text        VARCHAR(255)                            NOT NULL,
    correct     BOOLEAN                                 NOT NULL,
    question_id BIGINT,
    CONSTRAINT pk_option PRIMARY KEY (id)
);

ALTER TABLE option
    ADD CONSTRAINT FK_OPTION_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);
CREATE INDEX IF NOT EXISTS option_question ON option (question_id);

CREATE TABLE test_result
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    completed_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    employee_id  BIGINT,
    test_id      BIGINT,
    CONSTRAINT pk_test_result PRIMARY KEY (id)
);

ALTER TABLE test_result
    ADD CONSTRAINT FK_TEST_RESULT_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);
CREATE INDEX IF NOT EXISTS test_result_employee ON test_result (employee_id);

ALTER TABLE test_result
    ADD CONSTRAINT FK_TEST_RESULT_ON_TEST FOREIGN KEY (test_id) REFERENCES test (id);
CREATE INDEX IF NOT EXISTS test_result_test ON test_result (test_id);

CREATE TABLE test_result_detail
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_text   VARCHAR(255),
    selected_answer VARCHAR(255),
    correct_answer  VARCHAR(255),
    is_correct      BOOLEAN                                 NOT NULL,
    result_id       BIGINT,
    CONSTRAINT pk_test_result_detail PRIMARY KEY (id)
);

ALTER TABLE test_result_detail
    ADD CONSTRAINT FK_TEST_RESULT_DETAIL_ON_RESULT FOREIGN KEY (result_id) REFERENCES test_result (id);
CREATE INDEX IF NOT EXISTS test_result_detail_result_test ON test_result_detail (result_id);

CREATE TABLE employee_test_assignments
(
    deadline    TIMESTAMP WITHOUT TIME ZONE,
    status      SMALLINT,
    employee_id BIGINT NOT NULL,
    test_id     BIGINT NOT NULL,
    CONSTRAINT pk_employee_test_assignments PRIMARY KEY (employee_id, test_id)
);

ALTER TABLE employee_test_assignments
    ADD CONSTRAINT FK_EMPLOYEE_TEST_ASSIGNMENTS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);
CREATE INDEX IF NOT EXISTS employee_test_assignments_employee ON employee_test_assignments (employee_id);

ALTER TABLE employee_test_assignments
    ADD CONSTRAINT FK_EMPLOYEE_TEST_ASSIGNMENTS_ON_TEST FOREIGN KEY (test_id) REFERENCES test (id);
CREATE INDEX IF NOT EXISTS employee_test_assignments_test ON employee_test_assignments (test_id);

CREATE TABLE test_sessions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time  TIMESTAMP WITHOUT TIME ZONE,
    end_time    TIMESTAMP WITHOUT TIME ZONE,
    employee_id BIGINT,
    test_id     BIGINT,
    CONSTRAINT pk_test_sessions PRIMARY KEY (id)
);

ALTER TABLE test_sessions
    ADD CONSTRAINT FK_TEST_SESSIONS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);
CREATE INDEX IF NOT EXISTS test_sessions_employee ON test_sessions (employee_id);

ALTER TABLE test_sessions
    ADD CONSTRAINT FK_TEST_SESSIONS_ON_TEST FOREIGN KEY (test_id) REFERENCES test (id);
CREATE INDEX IF NOT EXISTS test_sessions_test ON test_sessions (test_id);


INSERT INTO scope (type)
VALUES ('TEST_CREATE');

INSERT INTO role_scopes (role_id, scopes_id)
SELECT r.id,
       (SELECT s.id FROM scope s WHERE type = 'TEST_CREATE')
FROM role r
WHERE name = 'Владелец';