version: '3.8'

services:
  db:
    image: postgres:latest        # Использование последней версии PostgreSQL
    container_name: springboot_db
    environment:
      POSTGRES_DB: homecrm     # Название вашей БД
      POSTGRES_USER: myuser       # Пользователь базы данных
      POSTGRES_PASSWORD: mypassword # Пароль пользователя
    ports:
      - "5432:5432"               # Открытие порта PostgreSQL наружу
    volumes:
      - pgdata:/var/lib/postgresql/data # Хранение данных PostgreSQL вне контейнера
  home-crm-back:
    image: ddobrovolskiy/home-crm-back:0.0.2
    container_name: home-crm-back
    restart: unless-stopped
    depends_on: # Зависимость от сервиса базы данных
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/homecrm
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update   # Автоматическое обновление схемы
      SPRING_JPA_SHOW_SQL: true                # Отображение SQL запросов
  home-crm-front:
    image: ddobrovolskiy/home-crm-front:0.0.4
    container_name: home-crm-front
    restart: unless-stopped
    ports:
      - "80:80"

volumes:
  pgdata: